// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.DeveloperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Blizzard Entertainment, Inc. is an American video game developer and publisher based in Irvine, California.",
                            Name = "Blizzard Entertainment",
                            StartedDate = new DateOnly(1991, 2, 1)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Valve Corporation is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington.",
                            Name = "Valve Corporation",
                            StartedDate = new DateOnly(1996, 8, 24)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rockstar Games, Inc. is an American video game publisher based in New York City.",
                            Name = "Rockstar Games",
                            StartedDate = new DateOnly(1998, 12, 1)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Electronic Arts Inc. is an American video game company headquartered in Redwood City, California.",
                            Name = "Electronic Arts",
                            StartedDate = new DateOnly(1982, 5, 28)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ubisoft Entertainment SA is a French video game company headquartered in Montreuil with several development studios across the world.",
                            Name = "Ubisoft",
                            StartedDate = new DateOnly(1986, 3, 12)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Square Enix Holdings Co., Ltd. is a Japanese video game developer, publisher, and distribution company known for its Final Fantasy, Dragon Quest, and Kingdom Hearts role-playing video game franchises.",
                            Name = "Square Enix",
                            StartedDate = new DateOnly(2003, 4, 1)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Capcom Co., Ltd. is a Japanese video game developer and publisher known for creating multi-million-selling franchises such as Resident Evil, Street Fighter, and Monster Hunter.",
                            Name = "Capcom",
                            StartedDate = new DateOnly(1979, 5, 30)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Naughty Dog, LLC is an American first-party video game developer based in Santa Monica, California.",
                            Name = "Naughty Dog",
                            StartedDate = new DateOnly(1984, 9, 27)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bungie, Inc. is an American video game developer based in Bellevue, Washington.",
                            Name = "Bungie",
                            StartedDate = new DateOnly(1991, 5, 1)
                        },
                        new
                        {
                            Id = 10,
                            Description = "CD Projekt Red is a Polish video game developer based in Warsaw, founded in 2002.",
                            Name = "CD Projekt Red",
                            StartedDate = new DateOnly(2002, 2, 1)
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bethesda Game Studios is an American video game developer and a studio of ZeniMax Media based in Rockville, Maryland.",
                            Name = "Bethesda Game Studios",
                            StartedDate = new DateOnly(2001, 10, 1)
                        });
                });

            modelBuilder.Entity("Data.Entities.GameDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameEntityId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GameEntityId")
                        .IsUnique();

                    b.ToTable("GameDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Diablo 2: Lord Of Destruction",
                            GameEntityId = 1,
                            ReleaseDate = new DateOnly(2000, 6, 30)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Half-Life 2",
                            GameEntityId = 2,
                            ReleaseDate = new DateOnly(2004, 11, 16)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Grand Theft Auto V",
                            GameEntityId = 3,
                            ReleaseDate = new DateOnly(2013, 9, 17)
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Sims 4",
                            GameEntityId = 4,
                            ReleaseDate = new DateOnly(2014, 9, 2)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Assassin's Creed Valhalla",
                            GameEntityId = 5,
                            ReleaseDate = new DateOnly(2020, 11, 10)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Final Fantasy XV",
                            GameEntityId = 6,
                            ReleaseDate = new DateOnly(2016, 11, 29)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Resident Evil Village",
                            GameEntityId = 7,
                            ReleaseDate = new DateOnly(2021, 5, 7)
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Last of Us Part II",
                            GameEntityId = 8,
                            ReleaseDate = new DateOnly(2020, 6, 19)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Destiny 2",
                            GameEntityId = 9,
                            ReleaseDate = new DateOnly(2017, 9, 6)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cyberpunk 2077",
                            GameEntityId = 10,
                            ReleaseDate = new DateOnly(2020, 12, 10)
                        });
                });

            modelBuilder.Entity("Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeveloperId = 1,
                            Title = "Diablo 2: Lord Of Destruction"
                        },
                        new
                        {
                            Id = 2,
                            DeveloperId = 2,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 3,
                            DeveloperId = 3,
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 4,
                            DeveloperId = 4,
                            Title = "The Sims 4"
                        },
                        new
                        {
                            Id = 5,
                            DeveloperId = 5,
                            Title = "Assassin's Creed Valhalla"
                        },
                        new
                        {
                            Id = 6,
                            DeveloperId = 6,
                            Title = "Final Fantasy XV"
                        },
                        new
                        {
                            Id = 7,
                            DeveloperId = 7,
                            Title = "Resident Evil Village"
                        },
                        new
                        {
                            Id = 8,
                            DeveloperId = 8,
                            Title = "The Last of Us Part II"
                        },
                        new
                        {
                            Id = 9,
                            DeveloperId = 9,
                            Title = "Destiny 2"
                        },
                        new
                        {
                            Id = 10,
                            DeveloperId = 10,
                            Title = "Cyberpunk 2077"
                        });
                });

            modelBuilder.Entity("Data.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "FPS"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "RPG"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Strategy"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Simulation"
                        });
                });

            modelBuilder.Entity("GameEntityGenreEntity", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameEntityGenreEntity");
                });

            modelBuilder.Entity("Data.Entities.GameDetails", b =>
                {
                    b.HasOne("Data.Entities.GameEntity", null)
                        .WithOne("Details")
                        .HasForeignKey("Data.Entities.GameDetails", "GameEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.GameEntity", b =>
                {
                    b.HasOne("Data.Entities.DeveloperEntity", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("GameEntityGenreEntity", b =>
                {
                    b.HasOne("Data.Entities.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.GameEntity", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
